/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-13 05:59:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardlist1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1701221558789L));
    _jspx_dependants.put("jar:file:/C:/jspwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/board/../footer.jsp", Long.valueOf(1702281196385L));
    _jspx_dependants.put("/board/../header.jsp", Long.valueOf(1702281578453L));
    _jspx_dependants.put("jar:file:/C:/jspwork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>여행 후기 게시판</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div id = \"header\">\r\n");
      out.write("		<div id=\"welcome\">\r\n");
      out.write("			<p>All travel information can be found in the YeoJeongDam !</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<nav>\r\n");
      out.write("		<div id=\"topMenu\">\r\n");
      out.write("			<div id=\"mainMenu\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"http://localhost:8080/main.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"#\">여행지</a>\r\n");
      out.write("						<div class=\"test\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">국내</a></li>\r\n");
      out.write("								<li><a href=\"#\">여행</a></li>\r\n");
      out.write("								<li><a href=\"#\">숙소 / 교통</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"#\">커뮤니티</a>\r\n");
      out.write("						<div class=\"test\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">여행 후기</a><a href=\"#\" id=\"a_1\">Q&A</a></li>\r\n");
      out.write("								<li><a href=\"#\">동행자 찾기</a><a href=\"#\" id=\"a_2\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"#\">나의 계획</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"#\">여정담</a>\r\n");
      out.write("						<div class=\"test\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">여정담 정보</a></li>\r\n");
      out.write("								<li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("								<li><a href=\"#\">멤버쉽</a></li>\r\n");
      out.write("								<li><a href=\"#\">자주하는 질문</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"sideMenu\">\r\n");
      out.write("				<ul id=\"sideMenu_1\">\r\n");
      out.write("					<li><a href=\"#\">로그인</a></li>\r\n");
      out.write("					<li><a href=\"http://localhost:8080/member/joinform01.jsp\">회원가입</a></li>\r\n");
      out.write("					<li><a href=\"#\"><i class=\"fa-solid fa-earth-americas\"></i>&nbsp;South Korea</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<ul id=\"sideMenu_2\">\r\n");
      out.write("					<li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("					<li><a href=\"#\">찜한 목록(0)</a></li>\r\n");
      out.write("					<li><a href=\"#\">English</a></li> <!-- 스크롤로 언어(영어/한국) 선택 -->\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"bottomMenu\">\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	<section class=\"notice\">\r\n");
      out.write("    <div class=\"board-title\">\r\n");
      out.write("        <div class=\"board\">\r\n");
      out.write("            <h3>여행 후기</h3>\r\n");
      out.write("            <p>게시판에 맞는 정보를 공유해주세요.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- board list area -->\r\n");
      out.write("    <div id=\"board-list\">\r\n");
      out.write("        <div class=\"board\">\r\n");
      out.write("            <table class=\"board-table\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th-num\">번호</th>\r\n");
      out.write("                        <th class=\"th-title\">제목</th>\r\n");
      out.write("                        <th class=\"th-id\">작성자</th>\r\n");
      out.write("                        <th class=\"th-date\">작성일</th>\r\n");
      out.write("                        <th class=\"th-hit\">조회수</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <!-- 인기글 테이블 내용 -->\r\n");
      out.write("                    <tr class=\"medal1\">\r\n");
      out.write("                        <td><img src=\"/resources/images/1.png\" alt=\"1등\" width=\"40\" height=\"40\"></td>\r\n");
      out.write("                        <td><a href=\"#!\">일본 오사카 3박 4일 총 경비 150만원<br>(2인)계획공유:)</a></td>\r\n");
      out.write("                        <td>임예은</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr class=\"medal2\">\r\n");
      out.write("                        <td><img src=\"/resources/images/2.png\" alt=\"2등\" width=\"40\" height=\"40\"></td>\r\n");
      out.write("                        <td><a href=\"#!\">즐겁게 다녀온 이탈리아 렌트카 후기<br>(16박 17일)</a></td>\r\n");
      out.write("                        <td>서지훈</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>100</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr class=\"medal3\">\r\n");
      out.write("                        <td><img src=\"/resources/images/3.png\" alt=\"3등\" width=\"40\" height=\"40\"></td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>100</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>12</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>11</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>9</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>8</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>7</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>6</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td><a href=\"#!\">제주도 한달 살이 후기</a></td>\r\n");
      out.write("                        <td>이나경</td>\r\n");
      out.write("                        <td>2023.12.08</td>\r\n");
      out.write("                        <td>114</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- 검색 -->\r\n");
      out.write("<div class=\"search-container\">\r\n");
      out.write("    <div class=\"input-wrapper\">\r\n");
      out.write("        <select id=\"search-select\">\r\n");
      out.write("            <option value=\"제목\">제목</option>\r\n");
      out.write("            <option value=\"작성자\">작성자</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <input type=\"text\" id=\"search-input\" placeholder=\"검색어를 입력하세요.\" size=\"30%\">\r\n");
      out.write("     <button id=\"search-button\">검색</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"button\" value=\"글쓰기\" id=\"write\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<footer>\r\n");
      out.write("	<ul id= footerMenu_left>\r\n");
      out.write("		<li><a href=\"\">개인정보 처리방침</a></li>\r\n");
      out.write("		<li><a href=\"\">이용약관</a></li>\r\n");
      out.write("		<li><a href=\"\">자주하는 질문</a></li>\r\n");
      out.write("		<li><a href=\"\">고객센터</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	\r\n");
      out.write("	<p>여정담</p>\r\n");
      out.write("	\r\n");
      out.write("	<ul id= footerMenu_right>\r\n");
      out.write("		<li><a href=\"\">인스타그램</a></li>\r\n");
      out.write("		<li><a href=\"\">© 여정담 2023.website by여정담</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
