/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-06 03:15:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Preview</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("      html, body {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        -webkit-font-smoothing: antialiased;\r\n");
      out.write("        -moz-osx-font-smoothing: grayscale;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div\r\n");
      out.write("      class=\"w-[1440px] h-[3230px] relative overflow-hidden\"\r\n");
      out.write("      style=\"filter: drop-shadow(0px 4px 4px rgba(0,0,0,0.25));\"\r\n");
      out.write("    >\r\n");
      out.write("      <div class=\"w-[358px] h-[418px] absolute left-[99px] top-[1694px]\">\r\n");
      out.write("        <div class=\"w-[1247.77px] h-[460.08px] absolute left-0 top-[-42px]\">\r\n");
      out.write("          <div class=\"w-[578px] h-[731px]\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"—pngtree—polaroid-photo-frame-transparent_8433985-1.png\"\r\n");
      out.write("              class=\"w-[578px] h-[731px] absolute left-[803.5px] top-[-37.5px] object-cover\"\r\n");
      out.write("            /><img\r\n");
      out.write("              class=\"w-[398px] h-[394px] absolute left-[894.5px] top-[92.5px]\"\r\n");
      out.write("              src=\"rectangle-22.png\"\r\n");
      out.write("            />\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"absolute left-[937px] top-[531px] text-2xl font-bold text-left text-[#676262]\"\r\n");
      out.write("            >\r\n");
      out.write("              제주에서\r\n");
      out.write("            </p>\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"location-1.png\"\r\n");
      out.write("              class=\"w-8 h-8 absolute left-[894.5px] top-[528.5px] object-cover\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"w-[578px] h-[731px]\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"—pngtree—polaroid-photo-frame-transparent_8433985-1.png\"\r\n");
      out.write("              class=\"w-[578px] h-[731px] absolute left-[334.5px] top-[-37.5px] object-cover\"\r\n");
      out.write("            /><img\r\n");
      out.write("              class=\"w-[396px] h-[391px] absolute left-[425.5px] top-[92.5px]\"\r\n");
      out.write("              src=\"rectangle-22-2.png\"\r\n");
      out.write("            />\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"absolute left-[468px] top-[531px] text-2xl font-bold text-left text-[#676262]\"\r\n");
      out.write("            >\r\n");
      out.write("              서울에서\r\n");
      out.write("            </p>\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"location-1.png\"\r\n");
      out.write("              class=\"w-8 h-8 absolute left-[425.5px] top-[528.5px] object-cover\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"w-[578px] h-[731px]\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"—pngtree—polaroid-photo-frame-transparent_8433985-1.png\"\r\n");
      out.write("              class=\"w-[578px] h-[731px] absolute left-[-143.5px] top-[-37.5px] object-cover\"\r\n");
      out.write("            /><img\r\n");
      out.write("              class=\"w-[396px] h-[394px] absolute left-[-52.5px] top-[92.5px]\"\r\n");
      out.write("              src=\"rectangle-22-3.png\"\r\n");
      out.write("            />\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"absolute left-[-10px] top-[531px] text-2xl font-bold text-left text-[#676262]\"\r\n");
      out.write("            >\r\n");
      out.write("              부산에서\r\n");
      out.write("            </p>\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"location-1.png\"\r\n");
      out.write("              class=\"w-8 h-8 absolute left-[-52.5px] top-[528.5px] object-cover\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w-[1200px] h-[250px] absolute left-[115px] top-[1111px]\">\r\n");
      out.write("        <p\r\n");
      out.write("          class=\"absolute left-[25px] top-[142px] text-[80px] font-medium text-left text-[#338ba7]\"\r\n");
      out.write("        >\r\n");
      out.write("          Nice place, With people you like.\r\n");
      out.write("        </p>\r\n");
      out.write("        <p class=\"absolute left-[25px] top-0 text-[80px] font-medium text-left text-[#338ba7]\">\r\n");
      out.write("          Life is part of a journey.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w-[920px] h-[19px] absolute left-[478px] top-[820px]\">\r\n");
      out.write("        <div class=\"w-40 h-[18px]\">\r\n");
      out.write("          <p class=\"absolute left-[904px] top-[3px] text-[11px] text-left text-[#df0505]\">0.43</p>\r\n");
      out.write("          <svg\r\n");
      out.write("            width=\"10\"\r\n");
      out.write("            height=\"8\"\r\n");
      out.write("            viewBox=\"0 0 10 8\"\r\n");
      out.write("            fill=\"none\"\r\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("            class=\"absolute left-[888.5px] top-[3.5px]\"\r\n");
      out.write("            preserveAspectRatio=\"none\"\r\n");
      out.write("          >\r\n");
      out.write("            <path d=\"M5 0L9.33013 7.5H0.669873L5 0Z\" fill=\"#DF0505\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <p class=\"absolute left-[838px] top-px text-sm text-left text-black\">182.24</p>\r\n");
      out.write("          <p class=\"absolute left-[767px] top-[-1px] text-base text-left text-black\">중국 CNY</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w-[156px] h-[18px]\">\r\n");
      out.write("          <p class=\"absolute left-[728px] top-[3px] text-[11px] text-left text-[#df0505]\">8.01</p>\r\n");
      out.write("          <svg\r\n");
      out.write("            width=\"10\"\r\n");
      out.write("            height=\"8\"\r\n");
      out.write("            viewBox=\"0 0 10 8\"\r\n");
      out.write("            fill=\"none\"\r\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("            class=\"absolute left-[712.5px] top-[3.5px]\"\r\n");
      out.write("            preserveAspectRatio=\"none\"\r\n");
      out.write("          >\r\n");
      out.write("            <path d=\"M5 0L9.33013 7.5H0.669873L5 0Z\" fill=\"#DF0505\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <p class=\"absolute left-[662px] top-px text-sm text-left text-black\">884.47</p>\r\n");
      out.write("          <p class=\"absolute left-[595px] top-0 text-base text-left text-black\">일본 JPY</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w-[175px] h-[18px]\">\r\n");
      out.write("          <p class=\"absolute left-[550px] top-[3px] text-[11px] text-left text-[#df0505]\">10.21</p>\r\n");
      out.write("          <svg\r\n");
      out.write("            width=\"10\"\r\n");
      out.write("            height=\"8\"\r\n");
      out.write("            viewBox=\"0 0 10 8\"\r\n");
      out.write("            fill=\"none\"\r\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("            class=\"absolute left-[534.5px] top-[4.5px]\"\r\n");
      out.write("            preserveAspectRatio=\"none\"\r\n");
      out.write("          >\r\n");
      out.write("            <path d=\"M5 0L9.33013 7.5H0.669873L5 0Z\" fill=\"#DF0505\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <p class=\"absolute left-[473px] top-0.5 text-sm text-left text-black\">1,650.38</p>\r\n");
      out.write("          <p class=\"absolute left-[404px] top-0 text-base text-left text-black\">영국 GBP</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w-[199px] h-[18px]\">\r\n");
      out.write("          <p class=\"absolute left-[365px] top-[5px] text-[11px] text-left text-[#0a05df]\">4.71</p>\r\n");
      out.write("          <svg\r\n");
      out.write("            width=\"10\"\r\n");
      out.write("            height=\"8\"\r\n");
      out.write("            viewBox=\"0 0 10 8\"\r\n");
      out.write("            fill=\"none\"\r\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("            class=\"absolute left-[359.5px] top-[13.5px]\"\r\n");
      out.write("            preserveAspectRatio=\"none\"\r\n");
      out.write("          >\r\n");
      out.write("            <path d=\"M5 8L0.669872 0.5L9.33013 0.5L5 8Z\" fill=\"#0A05DF\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <p class=\"absolute left-72 top-0.5 text-sm text-left text-black\">1,412.86</p>\r\n");
      out.write("          <p class=\"absolute left-[189px] top-0 text-base text-left text-black\">유럽연합 EUR</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"w-[169px] h-[18px]\">\r\n");
      out.write("          <p class=\"absolute left-[146px] top-[3px] text-[11px] text-left text-[#0a05df]\">2.00</p>\r\n");
      out.write("          <svg\r\n");
      out.write("            width=\"9\"\r\n");
      out.write("            height=\"8\"\r\n");
      out.write("            viewBox=\"0 0 9 8\"\r\n");
      out.write("            fill=\"none\"\r\n");
      out.write("            xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("            class=\"absolute left-[141.16px] top-3\"\r\n");
      out.write("            preserveAspectRatio=\"none\"\r\n");
      out.write("          >\r\n");
      out.write("            <path d=\"M4.33005 7.5L-7.43866e-05 0L8.66018 0L4.33005 7.5Z\" fill=\"#0A05DF\"></path>\r\n");
      out.write("          </svg>\r\n");
      out.write("          <p class=\"absolute left-[71px] top-px text-sm text-left text-black\">1,299.00</p>\r\n");
      out.write("          <p class=\"absolute left-0 top-0 text-base text-left text-black\">미국 USD</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w-[400px] h-[41px] absolute left-[41px] top-[803px] rounded-[20px]\">\r\n");
      out.write("        <svg\r\n");
      out.write("          width=\"408\"\r\n");
      out.write("          height=\"49\"\r\n");
      out.write("          viewBox=\"0 0 408 49\"\r\n");
      out.write("          fill=\"none\"\r\n");
      out.write("          xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("          class=\"absolute left-[-1px] top-[-1px]\"\r\n");
      out.write("          preserveAspectRatio=\"none\"\r\n");
      out.write("        >\r\n");
      out.write("          <g filter=\"url(#filter0_d_246_774)\">\r\n");
      out.write("            <path\r\n");
      out.write("              d=\"M4 20C4 8.95431 12.9543 0 24 0H204H304H384C395.046 0 404 8.95431 404 20V21C404 32.0457 395.046 41 384 41H24C12.9543 41 4 32.0457 4 21V20Z\"\r\n");
      out.write("              fill=\"url(#paint0_linear_246_774)\"\r\n");
      out.write("              fill-opacity=\"0.56\"\r\n");
      out.write("              shape-rendering=\"crispEdges\"\r\n");
      out.write("            ></path>\r\n");
      out.write("          </g>\r\n");
      out.write("          <defs>\r\n");
      out.write("            <filter\r\n");
      out.write("              id=\"filter0_d_246_774\"\r\n");
      out.write("              x=\"0\"\r\n");
      out.write("              y=\"0\"\r\n");
      out.write("              width=\"408\"\r\n");
      out.write("              height=\"49\"\r\n");
      out.write("              filterUnits=\"userSpaceOnUse\"\r\n");
      out.write("              color-interpolation-filters=\"sRGB\"\r\n");
      out.write("            >\r\n");
      out.write("              <feFlood flood-opacity=\"0\" result=\"BackgroundImageFix\"></feFlood>\r\n");
      out.write("              <feColorMatrix\r\n");
      out.write("                in=\"SourceAlpha\"\r\n");
      out.write("                type=\"matrix\"\r\n");
      out.write("                values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0\"\r\n");
      out.write("                result=\"hardAlpha\"\r\n");
      out.write("              ></feColorMatrix>\r\n");
      out.write("              <feOffset dy=\"4\"></feOffset>\r\n");
      out.write("              <feGaussianBlur stdDeviation=\"2\"></feGaussianBlur>\r\n");
      out.write("              <feComposite in2=\"hardAlpha\" operator=\"out\"></feComposite>\r\n");
      out.write("              <feColorMatrix\r\n");
      out.write("                type=\"matrix\"\r\n");
      out.write("                values=\"0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0\"\r\n");
      out.write("              ></feColorMatrix>\r\n");
      out.write("              <feBlend\r\n");
      out.write("                mode=\"normal\"\r\n");
      out.write("                in2=\"BackgroundImageFix\"\r\n");
      out.write("                result=\"effect1_dropShadow_246_774\"\r\n");
      out.write("              ></feBlend>\r\n");
      out.write("              <feBlend\r\n");
      out.write("                mode=\"normal\"\r\n");
      out.write("                in=\"SourceGraphic\"\r\n");
      out.write("                in2=\"effect1_dropShadow_246_774\"\r\n");
      out.write("                result=\"shape\"\r\n");
      out.write("              ></feBlend>\r\n");
      out.write("            </filter>\r\n");
      out.write("            <linearGradient\r\n");
      out.write("              id=\"paint0_linear_246_774\"\r\n");
      out.write("              x1=\"426.449\"\r\n");
      out.write("              y1=\"3.90476\"\r\n");
      out.write("              x2=\"426.449\"\r\n");
      out.write("              y2=\"44.9048\"\r\n");
      out.write("              gradientUnits=\"userSpaceOnUse\"\r\n");
      out.write("            >\r\n");
      out.write("              <stop offset=\"0.0001\" stop-color=\"#AFAFAF\"></stop>\r\n");
      out.write("              <stop offset=\"1\" stop-color=\"#D9D9D9\" stop-opacity=\"0\"></stop>\r\n");
      out.write("            </linearGradient>\r\n");
      out.write("          </defs>\r\n");
      out.write("        </svg>\r\n");
      out.write("        <p class=\"w-[163px] h-[18px] absolute left-4 top-3.5 text-sm text-left text-[#676565]\">\r\n");
      out.write("          검색어를 입력하세요.\r\n");
      out.write("        </p>\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"free-icon-magnifier-2866321-2.png\"\r\n");
      out.write("          class=\"w-[25px] h-6 absolute left-[360px] top-[7px] object-cover\"\r\n");
      out.write("        />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w-[1440px] h-[609px] absolute left-0 top-[2358px]\">\r\n");
      out.write("        <div class=\"flex justify-start items-start absolute left-0 top-[109px]\">\r\n");
      out.write("          <div class=\"flex-grow-0 flex-shrink-0 w-[480px] h-[500px]\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"w-[480px] h-[500px] absolute left-[-0.5px] top-[-0.5px] bg-[#cac8c8]\"\r\n");
      out.write("              style=\"box-shadow: 0px 4px 4px 0 rgba(0,0,0,0.25);\"\r\n");
      out.write("            ></div>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[295.15px] h-[28.33px] absolute left-[22px] top-[200.66px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              축구 좋아하시는 분, 같이 축구 보러 갑시다 !!\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[211.4px] h-[28.33px] absolute left-[22px] top-[157.33px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              12/5 ~ 12/12 부분 동행 구해요.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[300.26px] h-[28.33px] absolute left-[22px] top-[114px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              스페인 - 바르셀로나 여행자 1명 (여) 구해요 !\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"absolute left-[182px] top-[47px] text-xl font-bold text-left text-[#646161]\">\r\n");
      out.write("              동행자 찾기\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"flex-grow-0 flex-shrink-0 w-[480px] h-[500px]\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"w-[480px] h-[500px] absolute left-[479.5px] top-[-0.5px] bg-[#cac8c8]\"\r\n");
      out.write("              style=\"box-shadow: 0px 4px 4px 0 rgba(0,0,0,0.25);\"\r\n");
      out.write("            ></div>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[166.65px] h-[28.33px] absolute left-[511px] top-[200.67px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              제주도 한달 살이 후기\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[367.33px] h-[28.33px] absolute left-[511px] top-[157.33px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              즐겁게 다녀온 이탈리아 렌트카 후기 (16박 17일)\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[421.32px] h-[28.33px] absolute left-[511px] top-[114px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              일본 오사카 3박 4일 총 경비 150만원 (2인) 계획 공유 :)\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"absolute left-[680px] top-[47px] text-xl font-bold text-left text-[#646161]\">\r\n");
      out.write("              여행 후기\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"flex-grow-0 flex-shrink-0 w-[480px] h-[500px]\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"w-[480px] h-[500px] absolute left-[959.5px] top-[-0.5px] bg-[#cac8c8]\"\r\n");
      out.write("              style=\"box-shadow: 0px 4px 4px 0 rgba(0,0,0,0.25);\"\r\n");
      out.write("            ></div>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[165.48px] h-[28.33px] absolute left-[990px] top-[200.67px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              국내 배낭 여행 (20일)\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[222.98px] h-[28.33px] absolute left-[990px] top-[157.33px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              북유럽 여행 일정 (30박 32일)\r\n");
      out.write("            </p>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"w-[204.21px] h-[28.33px] absolute left-[990px] top-[114px] text-[15px] text-left text-black\"\r\n");
      out.write("            >\r\n");
      out.write("              요르단 여행 일정 (4박 5일)\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"absolute left-[1152px] top-[47px] text-xl font-bold text-left text-[#646161]\">\r\n");
      out.write("              나의 계획\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"absolute left-[61px] top-[49px] text-4xl font-bold text-left text-black\">\r\n");
      out.write("          인기글\r\n");
      out.write("        </p>\r\n");
      out.write("        <img src=\"hot-icon.png\" class=\"w-8 h-8 absolute left-[21px] top-[52px] object-cover\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"w-[1440px] h-[790px] absolute left-0 top-0\">\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"train-62849_1920-1.jpeg\"\r\n");
      out.write("          class=\"w-[1440px] h-[790px] absolute left-[-1px] top-[-1px] object-cover\"\r\n");
      out.write("        />\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"w-[72px] h-[25px] absolute left-[642px] top-[744px] rounded-[40px] bg-neutral-100\"\r\n");
      out.write("        ></div>\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"w-[23px] h-[21px] absolute left-[732px] top-[746px] rounded-[90px] bg-[#878585]\"\r\n");
      out.write("        ></div>\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"w-[22px] h-[21px] absolute left-[773px] top-[746px] rounded-[90px] bg-[#878585]\"\r\n");
      out.write("        ></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
