/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-14 08:07:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702537313542L));
    _jspx_dependants.put("jar:file:/C:/semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/teamwork/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입2</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/630c352365.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("<script src=\"../resources/js/validation.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\r\n");
      out.write("      <section id=\"joinform02\" >\r\n");
      out.write("      	\r\n");
      out.write("	  <div id=\"joinform02_box\">\r\n");
      out.write("	  	  <form action=\"/insertusers.do\" method=\"post\" name=\"users\">\r\n");
      out.write("		  <h2>회원 가입</h2>\r\n");
      out.write("		    	<ul>\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<label for=\"name\">닉네임</label>\r\n");
      out.write("		    			<input type=\"text\" id=\"id\" name=\"id\" \r\n");
      out.write("		    							placeholder=\"한글, 영문, 숫자만 사용해 주세요\">\r\n");
      out.write("						<div id=\"message\"></div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<label for=\"passwd\">비밀번호</label>\r\n");
      out.write("		    			<input type=\"password\" id=\"pw\" name=\"pw\" \r\n");
      out.write("		    							placeholder=\"영문, 숫자, 특수문자 조합 8~15자를 사용해주세요\">\r\n");
      out.write("		    			<div id=\"message\"></div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<label for=\"passwd2\">비밀번호 확인</label>\r\n");
      out.write("		    			<input type=\"password\" id=\"pw2\" name=\"pw2\">\r\n");
      out.write("		    			<div id=\"message\"></div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<label for=\"email\">이메일</label>\r\n");
      out.write("		    			<input type=\"text\" id=\"email\" name=\"email\" \r\n");
      out.write("		    				placeholder=\"이메일\"><span>@</span>\r\n");
      out.write("		    			<input class=\"domain_box\" id=\"domain-txt\" type=\"text\" name=\"domain-txt\"/>\r\n");
      out.write("							<select class=\"box\" id=\"domain-list\" >\r\n");
      out.write("							  <option value=\"type\">직접 입력</option>\r\n");
      out.write("							  <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("							  <option value=\"google.com\">google.com</option>\r\n");
      out.write("							  <option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("							  <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("							  <option value=\"kakao.com\">kakao.com</option>\r\n");
      out.write("							</select>\r\n");
      out.write("						<!-- 이메일 전체값 받는 input 박스 -->	\r\n");
      out.write("						<input type=\"hidden\" id=\"full-email\" name=\"full-email\" value=\"\">\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<div class=\"info\" id=\"info__birth\">\r\n");
      out.write("		    			<label for=\"birthday\">생년월일</label>\r\n");
      out.write("						  <select class=\"box\" id=\"birth-year\" name=\"birth-year\">\r\n");
      out.write("						    <option disabled selected>출생 연도</option>\r\n");
      out.write("						  </select>\r\n");
      out.write("						  <select class=\"box\" id=\"birth-month\" name=\"birth-month\">\r\n");
      out.write("						    <option disabled selected>월</option>\r\n");
      out.write("						  </select>\r\n");
      out.write("						  <select class=\"box\" id=\"birth-day\" name=\"birth-day\">\r\n");
      out.write("						    <option disabled selected>일</option>\r\n");
      out.write("						  </select>\r\n");
      out.write("						</div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<div class=\"tel\" id=\"tel_box\">\r\n");
      out.write("		    			<label for=\"tel\">전화번호</label>\r\n");
      out.write("						  <input type=\"text\" id=\"tel\" name=\"tel\" \r\n");
      out.write("		    				placeholder=\"' - '을 제외한 숫자를 입력해주세요\">\r\n");
      out.write("						</div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    		\r\n");
      out.write("		    		<li>\r\n");
      out.write("		    			<label for=\"gender\">성별</label>\r\n");
      out.write("		    			<div id=\"gender-option\">\r\n");
      out.write("			    			<input type=\"radio\" id=\"gender\" name=\"gender\" value=\"남\" checked>\r\n");
      out.write("			    			<p>남자</p>\r\n");
      out.write("			    			<input type=\"radio\" id=\"gender\" name=\"gender\" value=\"여\">\r\n");
      out.write("			    			<p>여자</p>\r\n");
      out.write("		    			</div>\r\n");
      out.write("		    		</li>\r\n");
      out.write("		    	</ul>\r\n");
      out.write("		    <div class=\"button\">\r\n");
      out.write("		    	<!-- checkMember(): 유효성 검사  -->\r\n");
      out.write("		    	<button type=\"submit\" onclick=\"checkUser()\">가입하기</button> \r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	</form>\r\n");
      out.write("	  	</div>\r\n");
      out.write("		  \r\n");
      out.write("	  </section>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
