/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-11 23:31:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원 가입1</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/630c352365.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"../resources/js/main.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write("\n");
      out.write("	<section id=\"joinform01\">\n");
      out.write("	\n");
      out.write("		<form id=\"joinform01_box\" action=\"http://localhost:8080/member/joinform02.jsp\" method=\"post\">\n");
      out.write("			<h2>약관 동의</h2>\n");
      out.write("			<div class=\"joinform01_checkbox\">\n");
      out.write("				<input type=\"checkbox\" id=\"all_agree\"/>\n");
      out.write("				<p>이용약관, 개인정보 수집 및 이용에 모두 동의합니다.</p>\n");
      out.write("			</div>\n");
      out.write("			<div><!-- 이용약관 -->\n");
      out.write("				<div class=\"joinform01_checkbox\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>이용약관 동의</p>\n");
      out.write("					<span class=\"essential\">(필수)</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"joinform01_contentBox\">\n");
      out.write("					<p>\n");
      out.write("						제 1 조 (목 적)\n");
      out.write("						\n");
      out.write("						이 서비스 이용약관(이하 “약관”이라 합니다)은 yeojeongdam Co.,Ltd.(이하 “회사”라 합니다)가 제공하는 서비스와 관련하여 회사와 이용 고객(또는 회원) 간에 서비스의 이용 조건 및 절차, 회사와 회원 간의 권리, 의무 및 책임 사항 기타 필요한 사항을 규정함을 목적으로 합니다.\n");
      out.write("						\n");
      out.write("						제 2 조 (용어의 정의)\n");
      out.write("						1. 서비스 : 이용 고객 또는 회원이 PC, TV, 휴대형 단말기 등 각종 유무선 기기 또는 프로그램을 통하여 이용할 수 있도록 회사가 제공하는 모든 인터넷 서비스를 말하며, 회사가 공개한 API를 이용하여 제3자가 개발 또는 구축한 프로그램이나 서비스를 통하여 이용 고객 또는 회원에게 제공되는 경우를 포함합니다.\n");
      out.write("						2. 회원 : 서비스에 접속하여 이 약관에 동의하고 ID와 비밀번호를 발급 받은 이용고객을 말합니다.\n");
      out.write("						3. ID(고유번호) : 회원의 식별과 회원의 서비스 이용을 위하여 회원이 선정하고 회사가 승인하는 영문자와 숫자의 조합을 말합니다.\n");
      out.write("						4. 비밀번호 : 회원의 회원정보 보호를 위해 회원 자신이 설정한 문자와 숫자의 조합을 말합니다.\n");
      out.write("						5. 도메인: 회원의 서비스 이용을 위하여 회원이 신청하여 회사가 부여한 고유한 인터넷 주소를 의미합니다. 회사는 제공하는 제반 서비스를 위해서 서비스에 따라 별도의 도메인 주소를 추가적으로 제공합니다.\n");
      out.write("						6. 게시물 : 회원이 회사가 제공하는 서비스에 게시 또는 등록하는 부호(URL 포함), 문자, 음성, 음향, 영상(동영상 포함),이미지(사진 포함), 파일 등을 말합니다.\n");
      out.write("						제 3 조 (약관의 효력 및 변경)\n");
      out.write("						1. 회사는 서비스의 가입 과정에 본 약관을 게시합니다.\n");
      out.write("						2. 회사는 관련법에 위배되지 않는 범위에서 본 약관을 변경할 수 있습니다.\n");
      out.write("						3. 회원은 회사가 전항에 따라 변경하는 약관에 동의하지 않을 권리가 있으며, 이 경우 회원은 회사에서 제공하는 서비스 이용 중단 및 탈퇴 의사를 표시하고 서비스 이용 종료를 요청할 수 있습니다. 다만, 회사가 회원에게 변경된 약관의 내용을 통보하면서 회원에게 \"7일 이내 의사 표시를 하지 않을 경우 의사 표시가 표명된 것으로 본다는 뜻\"을 명확히 통지하였음에도 불구하고, 거부의 의사표시를 하지 아니한 경우 회원이 변경된 약관에 동의하는 것으로 봅니다.\n");
      out.write("						4. 회원은 약관의 변경에 대하여 주의의무를 다하여야 하며, 변경된 약관의 부지로 인한 회원의 피해는 회사가 책임지지 않습니다.\n");
      out.write("						제 4 조 (약관 외 준칙)\n");
      out.write("						1. 회사는 제공하는 개별 서비스에 대해서 별도의 이용약관 및 정책을 둘 수 있으며, 해당 내용이 이 약관과 상충할 경우 개별 서비스의 이용약관을 우선하여 적용합니다.\n");
      out.write("						2. 본 약관에 명시되지 않은 사항이 관계법령에 규정되어 있을 경우에는 그 규정에 따릅니다.\n");
      out.write("						제 5 조 (이용계약의 성립)\n");
      out.write("						1. 이용계약은 회원이 본 서비스 및 제반 서비스에서 제공하는 회원 가입 페이지에서 서비스 이용약관에 동의한 후 이용신청을 하고 신청한 내용에 대해서 회사가 승낙함으로써 체결됩니다.\n");
      out.write("						2. 회사는 이용약관에 동의한 후 이용 신청한 사용자에 대해서 원칙적으로 접수 순서에 따라 서비스 이용을 승낙함을 원칙으로 합니다. 다만 업무 수행상 또는 기술상 지장이 있을 경우 일정시간 가입승인을 유보할 수 있습니다.\n");
      out.write("						3. 회사가 제공하는 서비스는 14세 미만의 아동을 위한 서비스가 아니며 회원이 본 서비스에 계정을 만들고 서비스를 이용하기 위해서는 14세 이상이어야 합니다.\n");
      out.write("						3. 회사는 다음 각 호에 해당하는 신청에 대해서 승낙하지 않거나 사후에 이용계약을 해지할 수 있습니다.\n");
      out.write("						\n");
      out.write("						- 가입신청자가 이 약관에 의하여 이전에 회원자격을 상실한 적이 있는 경우\n");
      out.write("						- 제3자의 전자우편 주소를 이용하여 신청한 경우\n");
      out.write("						- 허위의 정보를 기재하거나, 회사가 필수적으로 입력을 요청한 부분을 기재하지 않은 경우\n");
      out.write("						- 부정한 용도로 서비스를 사용하고자 하는 경우\n");
      out.write("						- 이용자의 귀책사유로 인하여 승인이 불가능하거나 기타 규정한 제반 사항을 위반하며 신청하는 경우\n");
      out.write("						- 회사의 정책에 적합하지 않는 회원으로 판단되는 경우나 서비스 제공이 곤란한 경우\n");
      out.write("						- 회원의 이용 목적이나 서비스 이용 방법이 회사의 재산권이나 영업권을 침해하거나 침해할 우려가 있는 경우\n");
      out.write("						- 비정상적인 방법을 통하여 아이디 및 도메인을 대량으로 생성하는 행위\n");
      out.write("						- 14세 미만의 아동이 법정대리인의 동의 없이 가입한 경우\n");
      out.write("						\n");
      out.write("						4. 회원은 회사에 언제든지 회원 탈퇴를 요청하여 이용계약을 해지할 수 있습니다.\n");
      out.write("						5. 회원은 회원 가입 시 기재한 개인정보의 내용에 변경이 발생한 경우, 즉시 변경사항을 정정하여 기재하여야 합니다. 변경의 지체로 인하여 발생한 회원의 손해에 대해 회사는 책임을 지지 않습니다.\n");
      out.write("						6. 회사는 관련 법률 및 회사의 개인정보취급방침에서 정한 바에 따라 회원에게 요청하는 회원정보 및 기타정보 항목을 추가, 삭제 등 변경하여 수집 및 이용 할 수 있습니다.\n");
      out.write("						\n");
      out.write("						제 6 조 (개인정보보호 의무)\n");
      out.write("						1. 회사는 정보통신망법 등 관계 법령이 정하는 바에 따라 회원의 개인정보를 보호하기 위해 노력합니다. 개인정보의 보호 및 사용에 대해서는 관련법 및 회사의 개인정보취급방침이 적용됩니다. 다만, 회사의 공식 사이트 이외의 링크된 사이트에서는 회사의 개인정보취급방침이 적용되지 않습니다.\n");
      out.write("						2. 회사는 서비스를 중단하거나 회원이 개인정보 제공 동의를 철회한 경우에는 신속하게 회원의 개인정보를 파기합니다. 단, 전자상거래 등에서의 소비자 보호에 관한 법률 등 관련 법률에서 정하는 바에 따라 일정 정보는 보관할 수 있습니다.\n");
      out.write("						3. 회사는 서비스 개선 및 회원 대상의 서비스 소개 등의 목적으로 회원의 동의 하에 관계 법령에서 정하는 바에 따라 추가적인 개인정보를 수집할 수 있습니다.\n");
      out.write("						4. 회사는 법률에 특별한 규정이 있는 경우를 제외하고는 회원의 별도 동의 없이 회원의 계정정보를 포함한 일체의 개인정보를 제3자에게 공개하거나 제공하지 아니합니다.\n");
      out.write("						5. 회사는 향후 제공하는 서비스에서 회원의 편의를 위해 회원의 계정 정보를 사용할 수 있도록 링크 및 기타 방법을 회원에게 제공 할 수 있습니다.\n");
      out.write("						\n");
      out.write("						제 7 조 (회원의 아이디 및 비밀번호)\n");
      out.write("						1. 회원은 아이디와 비밀번호에 관해서 관리책임이 있습니다.\n");
      out.write("						2. 회원은 아이디 및 비밀번호를 제3자가 이용하도록 제공하여서는 안됩니다.\n");
      out.write("						3. 회사는 회원이 아이디 및 비밀번호를 소홀히 관리하여 발생하는 서비스 이용상의 손해 또는 회사의 고의 또는 중대한 과실이 없는 제3자의 부정이용 등으로 인한 손해에 대해 책임을 지지 않습니다.\n");
      out.write("						4. 회원은 아이디 및 비밀번호가 도용되거나 제3자가 사용하고 있음을 인지한 경우에는 이를 즉시 회사에 통지하고 회사의 안내에 따라야 합니다.\n");
      out.write("						\n");
      out.write("						제 8 조 (회사의 의무)\n");
      out.write("						1.회사는 계속적이고 안정적인 서비스의 제공을 위하여 최선을 다하여 노력합니다.\n");
      out.write("						2. 회사는 회원이 안전하게 서비스를 이용할 수 있도록 현재 인터넷 보안기술의 발전수준과 회사가 제공하는 서비스의 성격에 적합한 보안시스템을 갖추고 운영해야 합니다.\n");
      out.write("						3. 회사는 서비스를 이용하는 회원으로부터 제기되는 의견이나 불만이 정당하다고 인정할 경우를 이를 처리 하여야 합니다. 이때 처리과정에 대해서 고객에게 메일 및 게시판 등의 방법으로 전달합니다.\n");
      out.write("						4. 회사는 정보통신망 이용촉진 및 정보보호에 관한 법률, 통신비밀보호법, 전기통신사업법 등 서비스의 운영, 유지와 관련 있는 법규를 준수합니다.\n");
      out.write("						\n");
      out.write("						제 9 조 (회원의 의무)\n");
      out.write("						1. 회원은 다음 각호에 해당하는 행위를 해서는 안됩니다.\n");
      out.write("						\n");
      out.write("						  1. 이용 신청 또는 회원정보 변경 시 허위내용 등록\n");
      out.write("						  2. 타인의 정보도용\n");
      out.write("						  3. 회사의 운영자, 임직원, 회사를 사칭하는 경우\n");
      out.write("						  4. 회사가 게시한 정보의 변경\n");
      out.write("						  5. 회사와 기타 제3자의 저작권, 영업비밀, 특허권 등 지적재산권에 대한 침해\n");
      out.write("						  6. 회사와 다른 회원 및 기타 제3자를 희롱하거나, 위협하거나 명예를 손상시키는 행위\n");
      out.write("						  7. 외설, 폭력적인 메시지, 기타 미풍양속에 반하는 정보를 공개 또는 게시하는 행위\n");
      out.write("						  8. 해킹을 통해서 다른 사용자의 정보를 취득하는 행위\n");
      out.write("						  9. 기타 현행 법령에 위반되는 불법적인 행위\n");
      out.write("						  10. 회사의 컨텐츠를 상업적인 목적으로 이용하거나 회사의 명시적인 허가 없이 로봇, 스파이더, 스크레이퍼나 기타 자동화된 수단이나 수동적인 과정을 이용하여 본 웹사이트의 콘텐츠나 정보를 열람, 감시 또는 복사하는 행위\n");
      out.write("						\n");
      out.write("						2. 회사는 회원이 전항에서 금지한 행위를 하는 경우, 위반 행위의 경중에 따라 서비스의 이용정지/계약의 해지 등 서비스 이용 제한, 수사 기관에 고발 조치 등 합당한 조치를 취할 수 있습니다.\n");
      out.write("						3. 회원은 회사의 명시적 사전 동의가 없는 한 서비스의 이용권한 및 기타 이용계약상의 지위를 제3자에게 양도, 증여, 대여할 수 없으며 이를 담보로 제공할 수 없습니다.\n");
      out.write("						4. 회원은 관계법, 이 약관의 규정, 이용안내 및 서비스와 관련하여 공지한 주의사항, 회사가 통지하는 사항 등을 준수하여야 하며, 기타 회사의 업무에 방해되는 행위를 하여서는 안 됩니다.\n");
      out.write("						5. 회원은 회사의 사전 허락 없이 회사가 정한 이용 목적과 방법에 반하여 영업/광고활동 등을 할 수 없고, 회원의 서비스 이용이 회사의 재산권, 영업권 또는 비즈니스 모델을 침해 하여서는 안됩니다.\n");
      out.write("						\n");
      out.write("						제 10 조 (서비스의 제공 및 변경)\n");
      out.write("						1. 회사는 정보통신설비의 보수점검, 교체 및 고장, 통신두절 또는 운영상 상당한 이유가 있는 경우 서비스의 제공을 일시적으로 중단할 수 있습니다. 이 경우 회사는 회원에게 공지사항 게시판 및 메일 등의 방법으로 통지합니다. 다만, 회사가 사전에 통지할 수 없는 부득이한 사유가 있는 경우 사후에 통지할 수 있습니다.\n");
      out.write("						2. 회사는 회원과 별도로 서면 계약을 체결하여 yeojeongdam.com (웹/모바일) 서비스 및 제반 서비스의 브랜드 특성을 이용할 수 있는 명시적인 권리를 부여하지 아니하는 한, 회원에게 회사 또는 서비스의 상호, 상표, 서비스표, 로고, 도메인 네임 및 기타 식별력 있는 브랜드 특성을 이용할 수 있는 권리를 부여하지 않습니다.\n");
      out.write("						3. 회사가 제공하는 서비스의 형태와 기능, 디자인 등 필요한 경우 수시로 변경되거나, 중단될 수 있습니다. 회사는 이 경우 개별적인 변경에 대해서 회원에게 사전 통지하지 않습니다. 다만, 회원에게 불리한 것으로 판단되는 경우 전자우편으로 통하여 이를 공지합니다.\n");
      out.write("						4. 전항에 의해서 제공되는 서비스가 변경 및 중단될 경우 무료로 제공되는 서비스에 대해서는 회원에게 별도로 보상하지 않습니다.\n");
      out.write("						\n");
      out.write("						제 11 조 (광고의 게재)\n");
      out.write("						1. 회사는 서비스 운영과 관련하여 회원정보, 고객이 입력한 정보를 활용하여 광고를 게재할 수 있습니다. 회원은 서비스 이용 시 노출되는 맞춤 광고 게재에 대해 동의합니다.\n");
      out.write("						2. 회사는 서비스상에 게재되어 있거나 서비스를 통한 광고주의 판촉활동에 회원이 참여하거나 교신 또는 거래를 함으로써 발생하는 손실과 손해에 대해 책임을 지지 않습니다.\n");
      out.write("						\n");
      out.write("						제 12 조 (전자우편을 통한 정보의 제공)\n");
      out.write("						1. 회사는 회원이 서비스 이용에 필요하다고 인정되는 다양한 정보를 회원이 제공한 전자우편 주소로 제공할 수 있습니다.\n");
      out.write("						2. 회사는 서비스 운영을 위해 회원정보를 활용하여 영리목적의 광고성 전자우편을 전송할 수 있습니다. 회원이 이를 원하지 않는 경우에는 언제든지 서비스 홈페이지 또는 서비스 내부 설정페이지 등을 통하여 수신거부를 할 수 있습니다.\n");
      out.write("						3. 회사는 다음 각호에 해당하는 경우 회원의 동의여부와 상관없이 전자우편으로 발송할 수 있습니다.\n");
      out.write("						\n");
      out.write("						- 이용 신청에서 입력한 전자우편 주소의 소유를 확인하기 위해서 인증메일을 발송하는 경우\n");
      out.write("						- 회원의 정보가 변경되어 확인하기 위해서 인증메일을 발송 하는 경우\n");
      out.write("						- 기타 서비스를 제공함에 있어 회원이 반드시 알아야 하는 중대한 정보라고 회사가 판단하는 경우\n");
      out.write("						\n");
      out.write("						제 13 조 (서비스 이용의 제한)\n");
      out.write("						1. 회사는 천재지변이나 국가비상사태, 해결이 곤란한 기술적 결함 또는 서비스 운영의 심각한 변화 등 불가항력적인 경우가 발생 또는 발생이 예상될 때는 서비스의 전부 또는 일부를 예고 없이 제한하거나 중지할 수 있습니다.\n");
      out.write("						2. 서비스를 이용하게 됨으로써 서비스 영역에서 발생하는 회원 사이의 문제에 대해 회사는 책임을 지지 않습니다.\n");
      out.write("						3. 회원의 관리 소홀로 인하여 ID 및 비밀번호의 유출로 인해 회원에게 서비스 이용상의 손해가 발생하거나 제3자에 의한 부정이용 등으로 회원의 의무조항을 위반한 경우 ID 및 해당 도메인의 이용이 제한될 수 있습니다.\n");
      out.write("						4. 회사가 본 약관 제9조의 위반 행위를 조사하는 과정에서 당해 회원 ID 및 도메인이 특정 위반행위에 직접적으로 관련되어 있는 경우 등 다른 회원의 권익 보호 및 서비스의 질서유지를 위해 불가피할 경우에는 해당 ID 및 도메인의 이용을 일시적으로 정지할 수 있습니다. 이에 대해 회원은 서비스 홈페이지 또는 전자 우편 등을 통해 이의신청을 할 수 있습니다.\n");
      out.write("						\n");
      out.write("						제 14 조 (게시물의 권리와 책임)\n");
      out.write("						1. 회원이 서비스 내에 작성한 텍스트, 이미지, 동영상, 링크 등의 기타 정보(이하 \"게시물\")에 대한 책임 및 권리는 게시물을 등록한 회원에게 있습니다.\n");
      out.write("						2. 회사는 회원이 작성한 콘텐츠에 대해서 감시 및 관리할 수 없으며 이에 대해서 책임지지 않습니다. 회사는 회원이 등록하는 게시물의 신뢰성, 진실성, 정확성 등에 대해서 책임지지 않으며 보증하지 않습니다.\n");
      out.write("						3. 서비스에 대한 저작권 및 지적재산권, 회사가 작성한 게시물의 저작권은 회사에 귀속됩니다. 단, 회원이 단독 또는 공동으로 작성한 게시물 및 제휴계약에 따라 제공된 저작물 등은 제외합니다. 회사의 서비스 내 콘텐츠나 그 일부의 복사, 전송, 복제, 재출판, 게시나 재배포는 회사의 사전 허락 없이는 금지됩니다.\n");
      out.write("						4. 회원이 서비스 내에 게시하는 게시물은 검색결과 내지 서비스 운영 및 홍보 등을 위해서 매체, 홈페이지, 기타의 방법(현재 알려져 있고 향후 개발되는 것을 포함)에서 사용될 수 있습니다. 이때 해당 노출을 위해 필요한 범위 내에서는 일부 수정, 복제, 편집되어 게시될 수 있습니다. 이 경우, 회사는 저작권법 규정을 준수하며, 회원은 언제든지 고객센터 또는 서비스 내 관리기능을 통해 해당 게시물에 대해 삭제, 검색결과 제외, 비공개 등의 조치를 취할 수 있습니다.\n");
      out.write("						5. 회원이 회원탈퇴를 한 경우에는 본인 도메인에 기록된 저작물 일체는 삭제됩니다. 단, 저작물이 서비스 내에 공식적으로 공개 등록된 게시물인 경우 해당 저작물이 계속 남아있을 수 있으며 공동 저작을 통해 작성된 경우에는 공동 저작자의 도메인에 해당 게시물이 남을 수 있고, 제3자에 의하여 보관되거나 무단복제 등을 통하여 복제됨으로써 해당 저작물이 삭제되지 않고 재 게시된 경우에 대하여 회사는 책임을 지지 않습니다. 또한, 본 약관 및 관계 법령을 위반한 회원의 경우 다른 회원을 보호하고, 법원, 수사기관 또는 관련 기관의 요청에 따른 증거자료로 활용하기 위해 회원탈퇴 후에도 관계 법령이 허용하는 한도에서 회원의 아이디 및 회원정보를 보관할 수 있습니다.\n");
      out.write("						6. 회원의 게시물 또는 저작물이 회사 또는 제3자의 저작권 등 지적재산권을 침해함으로써 발생하는 민∙형사상의 책임은 전적으로 회원이 부담해야 합니다.\n");
      out.write("						\n");
      out.write("						제 15 조 (게시물의 관리)\n");
      out.write("						1. 회원의 게시물이 정보통신망법 및 저작권 법 등 관련법에 위반되는 내용을 포함하는 경우, 권리자는 관련법이 정한 절차에 따라 해당 게시물의 게시중단 및 삭제 등을 요청할 수 있으며, 회사는 관련법에 따라 조치를 취하여야 합니다.\n");
      out.write("						2. 회사는 전항에 따른 권리자의 요청이 없는 경우라도 권리침해가 인정될 만한 사유가 있거나 본 약관 및 기타 회사 정책, 관련법에 위반되는 경우에는 관련법에 따라 해당 게시물에 대해 임시조치 등을 취할 수 있습니다.\n");
      out.write("						3. 회원이 비공개로 설정한 게시물에 대해서는 회사를 포함한 다른 사람이 열람할 수 없습니다. 단, 법원, 수사기관이나 기타 행정기관으로부터 정보제공을 요청 받은 경우나 기타 법률에 의해 요구되는 경우에는 회사를 포함한 다른 사람이 해당 게시물을 열람할 수 있습니다.\n");
      out.write("						4. 회원의 게시물이 선정적이거나 컴퓨터 바이러스 생성 등으로 타 회원에게 손해를 끼치거나 사생활 침해, 인종차별, 불법 행위 독려, 허위, 욕설, 비방, 왜곡, 위협, 도색적인 콘텐츠를 포함할 경우 회사는 사전 통보 없이 게시물을 수정하거나 삭제, 차단할 수 있습니다.\n");
      out.write("						\n");
      out.write("						제16조 (서비스 이용의 중지 및 해지)\n");
      out.write("						1. 회원은 회사에 언제든지 회원 탈퇴를 요청할 수 있으며, 회사는 이와 같은 요청을 받았을 경우, 회사가 별도로 고지한 방법에 따라 신속하게 처리합니다.\n");
      out.write("						2. 회원이 서비스의 이용중지를 원하는 경우에는 회사가 제공하는 서비스 페이지 또는 전자우편 등의 방법으로 회사에 중지신청을 할 수 있습니다. 회사는 이와 같은 요청을 받았을 경우, 회사가 별도로 고지한 방법에 따라 신속하게 처리합니다.\n");
      out.write("						3. 회사는 회원이 본 약관 제9조의 이용자의 의무를 위반한 경우 및 서비스의 정상적인 운영을 방해한 경우에는 사전 통보 후 회원 자격을 제한, 이용계약을 해지하거나 또는 기간을 정하여 서비스의 이용을 중지할 수 있습니다.\n");
      out.write("						4. 회사는 전항에도 불구하고, 저작권법 및 컴퓨터프로그램보호법을 위반한 불법프로그램의 제공 및 운영방해, 정보통신망법을 위반한 불법통신 및 해킹, 악성프로그램의 배포, 접속권한 초과행위 등과 같이 관련법을 위반한 경우에는 즉시 영구이용정지를 할 수 있습니다.\n");
      out.write("						5. 회사는 회원이 계속해서 3개월 이상 로그인하지 않는 경우, 회원정보의 보호 및 운영의 효율성을 위해 이용을 제한할 수 있습니다.\n");
      out.write("						6. 회원은 본 조에 따른 이용제한 등에 대해 회사가 정한 절차에 따라 이의신청을 할 수 있습니다. 이 때 이의가 정당하다고 회사가 인정하는 경우 회사는 즉시 서비스의 이용을 재개합니다.\n");
      out.write("						\n");
      out.write("						제 17조 (제3자 사이트 이용)\n");
      out.write("						회사는 본 서비스 내에 제3자들이 운영하는 웹사이트로 이동하는 하이퍼링크를 포함할 수 있습니다. 하이퍼링크는 회원의 참조를 위해서만 제공됩니다. '제3자 운영 사이트'는 당사가 회원의 편의를 위해 정보를 제공하는 항공, 호텔 등의 예약에 관한 사이트가 포함됩니다. 당사는 제3자 운영 사이트를 통해 제공되는 정보 (가격, 시간, 사진 등)의 정확성이나 신뢰도에 대하여 보장하지 않습니다. 이러한 제3자 사이트에서는 별로도 귀하의 개인정보를 요구하거나 결제를 요청하거나 회원가입을 유도할 수 있으므로 유의해 주시기 바라며 당사와는 별도의 이용약관과 개인정보취급방침으로 운영됩니다. 회사는 그런 웹사이트를 관리하지도 않고, 웹사이트의 콘텐츠나 개인정보 혹은 기타 업무수행에 대한 책임을 지지 않습니다. 또한 회원이 선택하는 링크나 회원이 다운로드 하는 소프트웨어(본 웹사이트나 다른 웹사이트에서)에 바이러스, 웜, 트로이 목마, 하자와 기타 파괴적인 프로그램이 없다는 것을 확인하는 예방조치를 취하는 것은 회원이 해야 할 일입니다. 웹사이트에 링크가 포함되어 있다고 하여 그러한 웹사이트의 자료에 대하여 보증하거나 그 운영자들과 어떤 관계가 있음을 내포하는 것은 아닙니다. 제3의 사이트 이용을 선택하는 것은 순수하게 회원의 선택사항이며 이 정보의 링크(제3의 사이트와의)에 대한 결정은 언제든지 취소할 수 있습니다\n");
      out.write("						\n");
      out.write("						제 18 조 (책임제한)\n");
      out.write("						1. 회사는 회원의 약관, 서비스 이용 방법 및 이용 기준을 준수하지 않는 등 회원의 귀책사유로 인한 서비스 이용의 장애에 대하여는 책임을 지지 않습니다.\n");
      out.write("						2. 회사는 서비스를 통하여 게재한 정보, 자료, 사실의 신뢰도, 정확성 등의 내용에 관하여는 보증하지 않습니다.\n");
      out.write("						3. 회사는 회원 간 또는 회원과 제3자 상호간에 서비스를 매개로 하여 거래 등을 한 경우에는 책임이 면제됩니다.\n");
      out.write("						4. 회사는 무료로 제공되는 서비스 내에 게시된 정보 및 서비스 이용과 관련하여 관련법에 특별한 규정이 없는 한 책임을 지지 않습니다.\n");
      out.write("						5. 회사는 천재지변, 전쟁, 기간통신사업자의 서비스 중지, 제3자가 제공하는 서비스의 인증 장애, 해결이 곤란한 기술적 결함 기타 불가항력으로 인하여 서비스를 제공할 수 없는 경우 책임이 면제됩니다.\n");
      out.write("						6. 회사는 사전에 공지된 서비스용 설비의 보수, 교체, 정기점검, 공사 등 부득이한 사유로 서비스가 중지되거나 장애가 발생한 경우에 대하서는 책임이 면제됩니다.\n");
      out.write("						7. 회사는 회원이 자신의 결정에 의하여 회사의 서비스를 사용하여 특정 프로그램이나 정보 등을 다운받거나 접근함으로써 입게 되는 컴퓨터 시스템상의 손해나 데이터, 정보의 상실에 대한 책임을 지지 않습니다.\n");
      out.write("						8. 회사는 기간통신사업자가 전기통신서비스를 중지하거나 정상적으로 제공하지 아니하여 손해가 발생한 경우에는 책임이 면제됩니다.\n");
      out.write("						9. 회원의 컴퓨터 오류, 신상정보 및 전자우편 주소의 부정확한 기재, 비밀번호 관리의 소홀 등 회원의 귀책사유로 인해 손해가 발생한 경우 회사는 책임을 지지 않습니다.\n");
      out.write("						10. 회사는 회원의 컴퓨터 환경이나 회사의 관리 범위에 있지 아니한 보안 문제로 인하여 발생하는 제반 문제 또는 현재의 보안기술 수준으로 방어가 곤란한 네트워크 해킹 등 회사의 귀책사유 없이 발생하는 문제에 대해서 책임을 지지 않습니다.\n");
      out.write("						11. 회사는 서비스가 제공한 내용에 대한 중요 정보의 정확성, 내용, 완전성, 적법성, 신뢰성 등에 대하여 보증하거나 책임을 지지 않으며, 사이트의 삭제, 저장실패, 잘못된 인도, 정보에 대한 제공에 대한 궁극적인 책임을 지지 않습니다. 또한, 회사는 회원이 서비스 내 또는 웹사이트상에 게시 또는 전송한 정보, 자료, 사실의 신뢰도, 정확성, 완결성, 품질 등 내용에 대해서는 책임을 지지 않습니다.\n");
      out.write("						12. 회사는 회원 상호간 또는 회원과 제 3자 상호 간에 서비스를 매개로 발생한 분쟁에 대해 개입할 의무가 없으며 이로 인한 손해를 배상할 책임도 없습니다.\n");
      out.write("						13. 회사는 회원이 서비스를 이용하여 기대하는 효용을 얻지 못한 것에 대하여 책임을 지지 않으며 서비스에 대한 취사선택 또는 이용으로 발생하는 손해 등에 대해서는 책임이 면제됩니다.\n");
      out.write("						14. 회사는 회원의 게시물을 등록 전에 사전심사 하거나 상시적으로 게시물의 내용을 확인 또는 검토하여야 할 의무가 없으며, 그 결과에 대한 책임을 지지 않습니다.\n");
      out.write("						\n");
      out.write("						제19조 (준거법 및 재판관할)\n");
      out.write("						1. 회사와 회원 간 제기된 소송에는 대한민국법을 준거법으로 합니다.\n");
      out.write("						2. 회사와 회원간 발생한 분쟁에 관한 소송은 민사소송법 상의 관할법원에 제소합니다.\n");
      out.write("						\n");
      out.write("						본 이용약관은 2023년 12 월 11 일부터 적용됩니다.\n");
      out.write("						개정된 이용약관의 적용일자 이전 가입자 또한 개정된 이용약관의 적용을 받습니다.\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			<div><!-- 개인정보 수집 -->\n");
      out.write("				<div class=\"joinform01_checkbox\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>개인정보 수집 및 이용 동의</p>\n");
      out.write("					<span class=\"essential\">(필수)</span>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"joinform01_contentBox\">\n");
      out.write("					<p>가. 개인정보의 수집 및 이용 목적\n");
      out.write(" \n");
      out.write("		                국가공간정보포털은 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 개인정보 보호법 제18조에 따라 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.\n");
      out.write("		        \n");
      out.write("		                나. 정보주체와 법정대리인의 권리ㆍ의무 및 행사방법\n");
      out.write("		                ① 정보주체(만 14세 미만인 경우에는 법정대리인을 말함)는 언제든지 개인정보 열람·정정·삭제·처리정지 요구 등의 권리를 행사할 수 있습니다.\n");
      out.write("		                ② 제1항에 따른 권리 행사는 개인정보보호법 시행규칙 별지 제8호 서식에 따라 작성 후 서면, 전자우편 등을 통하여 하실 수 있으며, 기관은 이에 대해 지체 없이 조치하겠습니다.\n");
      out.write("		                ③ 제1항에 따른 권리 행사는 정보주체의 법정대리인이나 위임을 받은 자 등 대리인을 통하여 하실 수 있습니다. 이 경우 개인정보 보호법 시행규칙 별지 제11호 서식에 따른 위임장을 제출하셔야 합니다.\n");
      out.write("		                ④ 개인정보 열람 및 처리정지 요구는 개인정보 보호법 제35조 제5항, 제37조 제2항에 의하여 정보주체의 권리가 제한 될 수 있습니다.\n");
      out.write("		                ⑤ 개인정보의 정정 및 삭제 요구는 다른 법령에서 그 개인정보가 수집 대상으로 명시되어 있는 경우에는 그 삭제를 요구할 수 없습니다.\n");
      out.write("		                ⑥ 정보주체 권리에 따른 열람의 요구, 정정ㆍ삭제의 요구, 처리정지의 요구 시 열람 등 요구를 한 자가 본인이거나 정당한 대리인인지를 확인합니다.\n");
      out.write("		                \n");
      out.write("		                다. 수집하는 개인정보의 항목\n");
      out.write("		                국가공간정보포털 회원정보(필수): 이름, 이메일(아이디), 비밀번호\n");
      out.write("		                \n");
      out.write("		                라. 개인정보의 보유 및 이용기간\n");
      out.write("		                국가공간정보포털은 법령에 따른 개인정보 보유ㆍ이용기간 또는 정보주체로부터 개인정보를 수집 시에 동의 받은 개인정보 보유ㆍ이용기간 내에서 개인정보를 처리ㆍ보유합니다.\n");
      out.write("		                \n");
      out.write("		                - 수집근거: 정보주체의 동의\n");
      out.write("		                - 보존기간: 회원 탈퇴 요청 전까지(1년 경과 시 재동의)\n");
      out.write("		                - 보존근거: 정보주체의 동의\n");
      out.write("		                \n");
      out.write("		                마. 동의 거부 권리 및 동의 거부에 따른 불이익\n");
      out.write("		                위 개인정보의 수집 및 이용에 대한 동의를 거부할 수 있으나, 동의를 거부할 경우 회원 가입이 제한됩니다.\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div><!-- 마케팅 -->\n");
      out.write("				<div class=\"joinform01_checkbox\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>마케팅 활용 동의 및 광고 수신 동의</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"joinform01_contentBox\">\n");
      out.write("					<p>제 1조(목적)\n");
      out.write("\n");
      out.write("					여정담 (이하 ‘회사’라 한다)의 yeojeongdam 운영에 관한 모든 관련 서비스(이하 ‘서비스’라 한다)는 회원님에게 보다 다양한 정보를 제공하고, 서비스의 질을 향상시키기 위하여 당사의 제휴사에게 「개인정보보호법」, 「정보통신망 이용촉진 및 정보보호 등에 관한 법률 」및 「신용정보의 이용 및 보호에 관한 법률」의 규정을 준수하여 회원님의 개인(신용)정보를 제3자에게 상품소개 및 홍보 등 영업목적으로 제공할 수 있습니다.\n");
      out.write("					\n");
      out.write("					제 2조(수집 및 활용 관련 정보)\n");
      out.write("					\n");
      out.write("					개인정보가 제공되는 비즈니스 파트너사, 제공 정보, 제공된 정보의 이용목적은 아래와 같습니다. 회원님들 중 이 개인정보의 제3자 마케팅 활용동의서 등에 동의하신 회원님들의 정보만이 제공되며, 제공된 정보는 명시된 이용목적을 벗어나 이용되지 않고, 개인정보의 유출 등 사고가 일어나지 않도록 더욱 철저한 보안이 이루어지도록 노력하고 있습니다.\n");
      out.write("					\n");
      out.write("					제 3조(제3자 정보제공의 동의 철회)\n");
      out.write("					\n");
      out.write("					본 동의서에 동의하고 가입하신 신규회원 중 제3자 정보제공을 철회하고 싶은 회원은 이미 제3자에게 제공된 개인정보라 하더라도, 언제든지 열람, 정정, 삭제를 요구할 수 있습니다. 열람, 정정, 삭제 및 정보제공 동의 철회는 뉴플로이 고객센터(02-6956-4660)를 통해 본인확인 후 요청할 수 있습니다. 해당 요청의 근거자료를 남기기 위해 해당 통화내역은 녹취될 수 있으며 회원은 이에 동의하는 것으로 간주합니다.\n");
      out.write("					\n");
      out.write("					이미 제공된 회원정보를 철회하는 데는 최대 10일의 기간이 소요됩니다. 활용동의 철회를 요청하시더라도 위와 같은 이유로 해당 철회 적용 이전까지 마케팅에 활용 될 수 있음을 알려드립니다.\n");
      out.write("					\n");
      out.write("					회사는 회원님의 소중한 정보를 보호하기 위하여 신속하게 처리되도록 최선의 노력을 다하겠습니다.\n");
      out.write("					\n");
      out.write("					(시행일) 이 약관은 2023년 12월 11일부터 시행합니다.\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"joinform01_checkbox\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>SMS 수신 동의</p>\n");
      out.write("					<p>(선택)</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"joinform01_checkbox\" id=\"joinform01_checkbox_email\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>E-mail 수신 동의</p>\n");
      out.write("					<p>(선택)</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"joinform01_checkbox\">\n");
      out.write("					<input type=\"checkbox\"/>\n");
      out.write("					<p>만 14세 이상입니다.</p>\n");
      out.write("					<span class=\"essential\">(필수)</span>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<button type=\"submit\" onclick=\"checkTerms()\">가입하기</button>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	\n");
      out.write("	</section>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
