/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2023-12-12 09:38:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1702372820000L));
    _jspx_dependants.put("jar:file:/C:/semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>메인 페이지</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/630c352365.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"resources/js/main.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("	<section id=\"main_container\">\n");
      out.write("	\n");
      out.write("		<div id =\"main\">\n");
      out.write("			<!-- 메인 이미지 -->\n");
      out.write("			<div id=\"main_img\">\n");
      out.write("				<div id=\"main_img\">\n");
      out.write("				    <img class=\"img_current\" src=\"resources/images/main_image01.png\" alt=\"배경\" style=\"position: absolute; top: 0; left: 0; opacity: 1;\">\n");
      out.write("    				<img class=\"img_next\" src=\"\" alt=\"배경\" style=\"position: absolute; top: 0; left: 0; opacity: 0; display: none;\">\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<!-- vscode -> imageslide.html , slide.js 참고 -->\n");
      out.write("			<!-- 슬라이드 도트 -->\n");
      out.write("				<div id=\"dots\">\n");
      out.write("					<div class=\"dot_active\"></div>\n");
      out.write("					<div class=\"dot\"></div>\n");
      out.write("					<div class=\"dot\"></div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			\n");
      out.write("			<div id=\"search_currency\">\n");
      out.write("				<!-- 검색창 -->\n");
      out.write("				<div class=\"search-box\">\n");
      out.write("				    <input type=\"text\" class=\"search-input\" placeholder=\"검색어를 입력하세요.\">\n");
      out.write("				    <button class=\"search-button\">\n");
      out.write("				        <img src=\"resources/images/magnifier.png\" alt=\"검색\"> <!-- 아이콘 대신 유니코드 문자를 사용 -->\n");
      out.write("				    </button>\n");
      out.write("				</div>\n");
      out.write("				<!-- 환율창 -->\n");
      out.write("				<div id=\"currency_box\">\n");
      out.write("					");
      out.write("\n");
      out.write("					 <p>미국 USD&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					 <p>일본 JPY&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					 <p>유럽연합 EUR&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("					 <p>중국 CNY&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<!-- 메인 문구 -->\n");
      out.write("			<div id=\"main_phrase\">\n");
      out.write("				<p>Life is part of a journey.</p><br>\n");
      out.write("				<p>Nice place, With people you like.</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<!-- 여행지 사진  -->\n");
      out.write("			<!-- 가로 슬라이드 : https://junhee6773.tistory.com/19 참고 -->\n");
      out.write("			<div id=\"main_pictures\">\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/busan.png\" alt=\"부산\">\n");
      out.write("			  		<p>부산에서</p>\n");
      out.write("			  	</div>\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/seoul.png\" alt=\"서울\">\n");
      out.write("			  		<p>서울에서</p>\n");
      out.write("			  	</div>\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/jeju.png\" alt=\"제주\">\n");
      out.write("			  		<p>제주에서</p>\n");
      out.write("			  	</div>\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/busan.png\" alt=\"부산\">\n");
      out.write("			  		<p>부산에서</p>\n");
      out.write("			  	</div>\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/busan.png\" alt=\"부산\">\n");
      out.write("			  		<p>부산에서</p>\n");
      out.write("			  	</div>\n");
      out.write("				<div>\n");
      out.write("					<img src=\"resources/images/busan.png\" alt=\"부산\">\n");
      out.write("			  		<p>부산에서</p>\n");
      out.write("			  	</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<!-- 커뮤니티 -->\n");
      out.write("			\n");
      out.write("			<div id=\"main_community\">\n");
      out.write("				<div id=\"main_community_title\">\n");
      out.write("					<img src=\"resources/images/hot.png\" alt=\"불\">\n");
      out.write("					<p>인기글</p>\n");
      out.write("				</div>\n");
      out.write("				<div id=\"main_community_boxes\">\n");
      out.write("					<div id=\"main_community_box\">\n");
      out.write("						<p class=\"main_community_content_title\">동행자 찾기</p>\n");
      out.write("						<div class=\"main_community_content\">	\n");
      out.write("							<h3>인기글</h3>\n");
      out.write("							<p><a href=\"#\">스페인 - 바르셀로나 여행자 1명 (여) 구해</a>\n");
      out.write("							<p><a href=\"#\">12/5 ~ 12/12 부분 동행 구해요.</a>\n");
      out.write("							<p><a href=\"#\">축구 좋아하시는 분, 같이 축구 보러 갑시다</a>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"main_community_content\" id=\"main_community_content_bottom\">\n");
      out.write("							<h3>최신글</h3>	\n");
      out.write("							<p><a href=\"#\">스페인 - 바르셀로나 여행자 1명 (여) 구해</a>\n");
      out.write("							<p><a href=\"#\">12/5 ~ 12/12 부분 동행 구해요.</a>\n");
      out.write("							<p><a href=\"#\">축구 좋아하시는 분, 같이 축구 보러 갑시다</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div id=\"main_community_box\">\n");
      out.write("						<p class=\"main_community_content_title\">여행 후기</p>\n");
      out.write("						<div class=\"main_community_content\" >\n");
      out.write("							<h3>인기글</h3>\n");
      out.write("							<p><a href=\"#\">일본 오사카 3박 4일 총 경비 150만원 (2인) 계획 공유 :)</a>\n");
      out.write("							<p><a href=\"#\">즐겁게 다녀온 이탈리아 렌트카 후기 (16박 17일)</a>\n");
      out.write("							<p><a href=\"#\">제주도 한달 살이 후기</a>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"main_community_content\" id=\"main_community_content_bottom\">\n");
      out.write("							<h3>최신글</h3>	\n");
      out.write("							<p><a href=\"#\">일본 오사카 3박 4일 총 경비 150만원 (2인) 계획 공유 :)</a>\n");
      out.write("							<p><a href=\"#\">즐겁게 다녀온 이탈리아 렌트카 후기 (16박 17일)</a>\n");
      out.write("							<p><a href=\"#\">제주도 한달 살이 후기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div id=\"main_community_box\">\n");
      out.write("						<p class=\"main_community_content_title\">나의 계획</p>\n");
      out.write("						<div class=\"main_community_content\">\n");
      out.write("							<h3>인기글</h3>\n");
      out.write("							<p><a href=\"#\">요르단 여행 일정 (4박 5일)</a>\n");
      out.write("							<p><a href=\"#\">북유럽 여행 일정 (30박 32일)</a>\n");
      out.write("							<p><a href=\"#\">국내 배낭 여행 (20일)</a>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"main_community_content\" id=\"main_community_content_bottom\">\n");
      out.write("							<h3>최신글</h3>	\n");
      out.write("							<p><a href=\"#\">요르단 여행 일정 (4박 5일)</a>\n");
      out.write("							<p><a href=\"#\">북유럽 여행 일정 (30박 32일)</a>\n");
      out.write("							<p><a href=\"#\">국내 배낭 여행 (20일)</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</section>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
